### ISSUE TITLE
Things to-do to make this an R package

### ISSUE THREAD

**Issue by willpearse** [TARobison/ReFernment#1]
- [x] Package structure
  - [x] Create sub-folders and files (R, man, DESCRIPTION, etc.)
  - [x] Check package dependencies
  - [x] Structure DESCRIPTION
  - [x] Split functions into different files (perhaps one or two 'main' functions, and a 'utilities' file
- [x] Documentation
  - [x] Make roxygen2 descriptions for every user-facing function
  - [x] Make examples for each user-facing function in roxygen format
  - [x] Upload 'demo' data (see https://github.com/willpearse/pez/tree/master/data and https://github.com/willpearse/pez/blob/master/R/laja.R for examples of how to format)
  - [x] Create vignette using `knitr` in HTML/PDF format. Short, sharp, and sweet, but use it to give a walk-through of what's going on
- [x] Unit and continuous integration tests (ugh)
  - [x] Get project on travis.ci (example of config file: https://github.com/willpearse/natdb/blob/master/.travis.yml)
  - [x] Add travis badge to README.md (e.g., https://raw.githubusercontent.com/willpearse/natdb/master/README.md)
  - [x] Add unit tests - no need to go overboard, but use the examples you've got to build them (e.g., https://github.com/willpearse/pez/tree/master/inst/tests)
- [x] Final checks
  - [x] Make sure package passes `R CMD build ReFernment` followed by `R CMD check ReFernment_1.0-0.tar.gz` or whatever
  - [x] Make sure package passes `R CMD check ReFernment_1.0-0.tar.gz --as-cran` (get it to pass the easier check first!)
  - [x] Check package on CRAN's servers (here? can't remember: https://win-builder.r-project.org/upload.aspx)
